name: 'CodeQL Languages'
description: 'Gets the list of CodeQL-supported languages in a repo.'
author: '@mbaluda'
outputs:
  languages:
    description: 'CodeQL-supported languages in the repo'
runs:
  using: 'node16'
  main: 'dist/index.js'
